#! /usr/bin/python

import click
import runpy

@click.command()
@click.option("-dh", "--devhints", "query", help="generate a cheatsheet from devhints.io")
def cheatsheet():
  runpy.run_path("./lib/cheatsheet.py devhints")

if __name__ == "__main__":
  cheatsheet()
